name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8465b7c708488ca5b9322eb5c2ceb21367e3d130b2322a78d03897f4cb4d070"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
