name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6138c509b5f7a3faeec19d0627c891590a5324d7162685f47de51245bb6ffbd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
