name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c74ed8ddf43facf50cdb574ae54a432aac9b826ffd6b9fd97e37af16ed7238de"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
