name = "Terra SMP S3"
author = "waffle"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14e5c56b58a06696b9187fc475f1ef716965786ff64467bc5235af5d52234cfd"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
