name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c224e39c4afe77e880cb8b04d662524ab7dcbc6ddef1eb2c259bf7fe4e586fba"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
