name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1e2eba53f57faba4b88d7950bd77bdbf2e418ae4ca532b299ba5ac3cdb21636"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
