name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fad99b6944f2cfe58f62fc80f63916d5b77a1bec42bf1b69fb349211682bb62"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
