name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dddb9b9aff1ae801bc7b9495b2411c040bcd0a75e1f792ad4394db7bd5d67577"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
