name = "Terra SMP S3"
author = "waffle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "117ffb941a160d738141622df190894d8ab704130f603a3c86a386bf1bff826b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
